version: 2

sources:
  - name: staging_source
    schema: staging
    tables:
      - name: test_1
        columns:
          - name: labels
            tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_in_set:
                  value_set: [0, 1]
                  quote_values: false   # tránh '0','1' (text) so với bigint

          - name: input_ids
            tests:
              - not_null

          - name: attention_mask
            tests:
              - not_null
